name: hexcrawl
services:
  website:
    image: nginx
    container_name: website
    networks:
      - default
    ports:
      - 80:80
    volumes:
      - /Users/ryankinal/projects/personal/dnd/hexcrawl:/var/www
      - /Users/ryankinal/projects/docker/hexcrawl/sites-available:/etc/nginx/conf.d
  api:
    image: node
    container_name: api
    working_dir: /usr/app
    command: npm run dev
    depends_on:
      - ddb
    environment:
      - ENVIRONMENT=dev
      - AWS_CREDENTIALS_FILE=/home/app/.aws/credentials
      - AWS_COGNITO_CLIENT_ID=2o3rkha4jvb0ad6qer5gvf627
      - AWS_COGNITO_CLIENT_SECRET=14bmal5uuas0h7nim8k6nbru0bo8ldb909b732g0l2ei2sdufn2r
      - AWS_COGNITO_POOL_ID=us-west-2_iUmV9VZmy
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - /Users/ryankinal/projects/personal/dnd/hexcrawl/api:/usr/app
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
  ddb:
    container_name: ddb
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal